### ISSUE TITLE
Bounding box not align with the actual object

### ISSUE THREAD

**Issue by coranholmes** [mikel-brostrom/Yolov5_DeepSort_Pytorch#331]
Thank you for the awesome work!

I don't really change the deepsort component but only change the config to 
```
DEEPSORT:
  REID_CKPT: "deep_sort/deep_sort/deep/checkpoint/ckpt.t7"
  MAX_DIST: 0.2
  MIN_CONFIDENCE: 0.3
  NMS_MAX_OVERLAP: 0.9
  MAX_IOU_DISTANCE: 0.5  # default 0.7
  MAX_AGE: 5  # default 70
  N_INIT: 3
  NN_BUDGET: 50  # default 100
```

I also change the visualization part to print more information which I believe is not relevant in this case. My issue here is I track every 25frames, the 2 consecutive track results (frame475 and frame500) are as follow:
![475](https://user-images.githubusercontent.com/2607616/158563110-0cc510ef-1821-4dd2-ab97-bd81674f6f86.jpg)
![500](https://user-images.githubusercontent.com/2607616/158563211-a67bac88-8b5a-40be-a87d-8f5f1425e801.jpg)

It is a bit wired to me that the bounding box in the second frame does not align with the actual vehicle? Is there a way to fix this? Thank you in advance.
